server: 
  port: 9001
spring: 
  application:  
    name: tensquare-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_article?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: lll757022544
  jpa: 
    database: MySQL
    show-sql: true
